version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ../../00.portfolio_production/env_postgres       
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - pg_data:/var/lib/postgres/data
    networks:
      - mynet      

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-XGET", "http://elastic:${ELASTIC_PASSWORD}@localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    env_file:
      - ../../00.portfolio_production/env_elastic      
    environment:
      - discovery.type=single-node
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - mynet

  app:
    container_name: portfolio
    build:
      context: /home/roque/03. Projects/00.portfolio
      dockerfile: ./docker/dockerfile
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/~/health/"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5000:5000"
    env_file:
      - ../../00.portfolio_production/env_portfolio  
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy          
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch:elasticsearch
      - postgres:postgres
    networks:
      - mynet    
    volumes:
      - ../../00.portfolio_production/portfolio_content/content.xlsx:/portfolio/mounted/content.xlsx 
      - ../../00.portfolio_production/portfolio_content/portfolio/static/img/:/portfolio/mounted/img/

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    container_name: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 30s    
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      postgres:
        condition: service_healthy          
      elasticsearch:
        condition: service_healthy
      app:
        condition: service_healthy
    networks:
      - mynet
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/      

networks:
  mynet:
    driver: bridge

volumes:
  pg_data:
  es_data:
    




