#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL			
	SELECT 'CREATE DATABASE $POSTGRES_DB' 
	   WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DB')\gexec	
		
	$$
	BEGIN
		IF NOT EXISTS (
				SELECT FROM pg_catalog.pgroles
				WHERE rolname = $POSTGRES_USER) THEN

			CREATE ROLE $POSTGRES_USER LOGIN PASSWORD '$POSTGRES_PASSWORD';
		END IF;
	END
	$$;

	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL