"""empty message

Revision ID: 0de3bdfb4c7b
Revises: 769bea0ea762
Create Date: 2023-09-06 20:04:24.927198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de3bdfb4c7b'
down_revision = '769bea0ea762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
