"""modifiying initial tables

Revision ID: 0e043c02ee6c
Revises: e75c8b8ab282
Create Date: 2023-08-24 18:47:06.235857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e043c02ee6c'
down_revision = 'e75c8b8ab282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=150), nullable=True))
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('link')

    # ### end Alembic commands ###
