"""empty message

Revision ID: 3365b5e8de69
Revises: 3a57dd327459
Create Date: 2023-10-01 19:45:31.875128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3365b5e8de69'
down_revision = '3a57dd327459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
