"""empty message

Revision ID: 368d2356296e
Revises: b7a75b6ea4f9
Create Date: 2023-09-11 14:36:57.369161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368d2356296e'
down_revision = 'b7a75b6ea4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_projects_title_slug'), ['title_slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_title_slug'))

    # ### end Alembic commands ###
