"""Change name to Portfolio

Revision ID: 46a4e16c27c0
Revises: 39df14424c6a
Create Date: 2023-08-25 18:14:31.294573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a4e16c27c0'
down_revision = '39df14424c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=20), nullable=True),
    sa.Column('variable', sa.String(length=20), nullable=True),
    sa.Column('languageid', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=250), nullable=True),
    sa.Column('link', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['languageid'], ['languages.id'], name='fk_languageid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_content_template'), ['template'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_content_variable'), ['variable'], unique=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_template')
        batch_op.drop_index('ix_portfolio_variable')

    op.drop_table('portfolio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template', sa.VARCHAR(length=20), nullable=True),
    sa.Column('variable', sa.VARCHAR(length=20), nullable=True),
    sa.Column('languageid', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.VARCHAR(length=250), nullable=True),
    sa.Column('link', sa.VARCHAR(length=150), nullable=True),
    sa.ForeignKeyConstraint(['languageid'], ['languages.id'], name='fk_languageid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_variable', ['variable'], unique=False)
        batch_op.create_index('ix_portfolio_template', ['template'], unique=False)

    with op.batch_alter_table('portfolio_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_content_variable'))
        batch_op.drop_index(batch_op.f('ix_portfolio_content_template'))

    op.drop_table('portfolio_content')
    # ### end Alembic commands ###
