"""empty message

Revision ID: 769bea0ea762
Revises: b1e2e4908f01
Create Date: 2023-09-05 20:49:08.851800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769bea0ea762'
down_revision = 'b1e2e4908f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_n', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_portfolio_projects_keywords'), ['keywords'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_keywords'))
        batch_op.drop_column('project_n')

    # ### end Alembic commands ###
