"""Initial migration

Revision ID: abe4a001394d
Revises: 
Create Date: 2023-09-11 20:06:42.903822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe4a001394d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_language'), ['language'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('portfolio_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=20), nullable=True),
    sa.Column('variable', sa.String(length=20), nullable=True),
    sa.Column('languageid', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['languageid'], ['languages.id'], name='fk_languageid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_content_template'), ['template'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_content_variable'), ['variable'], unique=False)

    op.create_table('portfolio_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('project_n', sa.Integer(), nullable=True),
    sa.Column('languageid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('title_slug', sa.String(length=60), nullable=False),
    sa.Column('resume', sa.String(length=250), nullable=True),
    sa.Column('exposition', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(length=250), nullable=True),
    sa.Column('link1', sa.String(length=250), nullable=True),
    sa.Column('link2', sa.String(length=250), nullable=True),
    sa.Column('link3', sa.String(length=250), nullable=True),
    sa.Column('link4', sa.String(length=250), nullable=True),
    sa.Column('link5', sa.String(length=250), nullable=True),
    sa.Column('image1', sa.String(length=50), nullable=True),
    sa.Column('image2', sa.String(length=50), nullable=True),
    sa.Column('image3', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['languageid'], ['languages.id'], name='fk_languageid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_projects_keywords'), ['keywords'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_projects_resume'), ['resume'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_projects_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_projects_title_slug'), ['title_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_title_slug'))
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_title'))
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_resume'))
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_keywords'))

    op.drop_table('portfolio_projects')
    with op.batch_alter_table('portfolio_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_content_variable'))
        batch_op.drop_index(batch_op.f('ix_portfolio_content_template'))

    op.drop_table('portfolio_content')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_language'))

    op.drop_table('languages')
    # ### end Alembic commands ###
