"""empty message

Revision ID: b1e2e4908f01
Revises: 4e7fcf8a60ba
Create Date: 2023-09-05 20:27:38.038939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e2e4908f01'
down_revision = '4e7fcf8a60ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('languageid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('resume', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(length=250), nullable=True),
    sa.Column('link1', sa.String(length=250), nullable=True),
    sa.Column('link2', sa.String(length=250), nullable=True),
    sa.Column('link3', sa.String(length=250), nullable=True),
    sa.Column('link4', sa.String(length=250), nullable=True),
    sa.Column('link5', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['languageid'], ['languages.id'], name='fk_languageid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_projects_resume'), ['resume'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_projects_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_title'))
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_resume'))

    op.drop_table('portfolio_projects')
    # ### end Alembic commands ###
