"""initial tables

Revision ID: e75c8b8ab282
Revises: 
Create Date: 2023-08-23 20:44:33.421672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75c8b8ab282'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_language'), ['language'], unique=True)

    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=20), nullable=True),
    sa.Column('variable', sa.String(length=20), nullable=True),
    sa.Column('languageid', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['languageid'], ['languages.id'], name='fk_languageid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_template'), ['template'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_variable'), ['variable'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_variable'))
        batch_op.drop_index(batch_op.f('ix_portfolio_template'))

    op.drop_table('portfolio')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_language'))

    op.drop_table('languages')
    # ### end Alembic commands ###
